### ISSUE TITLE
ActionView::Template::Error (Unable to find input class for enum)

### ISSUE THREAD

**Issue by r10r** [adzap/active_enum#24]
Hi,

I get an error from formtastic. What am I doing wrong?
- Created the enum classes in the initializer.
- used 'enumerate' to enumerate the model attribute

<pre>
ActionView::Template::Error (Unable to find input class for enum):
    1: <%= semantic_form_for @filter_rule do |f| %>
    2:     <%= f.inputs %>
    3:     <%= f.actions %>
    4: <% end %>
  app/views/filter_rules/_form.html.erb:2:in `block in _app_views_filter_rules__form_html_erb___1761557587620786887_70204566903900'
  app/views/filter_rules/_form.html.erb:1:in `_app_views_filter_rules__form_html_erb___1761557587620786887_70204566903900'
  app/views/filter_rules/new.html.erb:5:in `_app_views_filter_rules_new_html_erb__965338666889571281_70204566763960'
  app/controllers/filter_rules_controller.rb:29:in `new'
</pre>

I've verified that the form helper is included:

<pre>
[ruben@rauscher mailtables]$ tail /Users/ruben/.rvm/gems/ruby-1.9.3-p392/gems/active_enum-0.9.12/lib/active_enum/form_helpers/formtastic2.rb
        super
      end

    end
  end
end

puts "foooooooooo"
Formtastic::FormBuilder.send :include, ActiveEnum::FormHelpers::Formtastic2
p Formtastic::FormBuilder.included_modules
[ruben@rauscher mailtables]$ be rails server
=> Booting WEBrick
=> Rails 3.2.13 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
foooooooooo
[ActiveEnum::FormHelpers::Formtastic2, Formtastic::Helpers::ErrorsHelper, Formtastic::Helpers::ActionsHelper, Formtastic::Helpers::ActionHelper, Formtastic::Helpers::InputsHelper, Formtastic::LocalizedString, Formtastic::Helpers::FieldsetWrapper, Formtastic::Helpers::InputHelper, Formtastic::Helpers::FileColumnDetection, Formtastic::Helpers::Reflection, Formtastic::HtmlAttributes, JSON::Ext::Generator::GeneratorMethods::Object, ActiveSupport::Dependencies::Loadable, V8::Conversion::Object, Kernel]
</pre>

content of the initializer:
<pre>
ActiveEnum.setup do |config|

  # Extend classes to add enumerate method
  config.extend_classes = [ ActiveRecord::Base ]

  # Return name string as value for attribute method
  config.use_name_as_value = true

  # Storage of values (:memory, :i18n)
  config.storage = :memory

  require 'active_enum/form_helpers/formtastic2'
end

ActiveEnum.define do
  enum(:chain) do
    value :id => 1, :name => 'templates'
    value :id => 2, :name => 'global'
    value :id => 3, :name => 'routing'
    value :id => 4, :name => 'transport'
  end

  enum(:policy) do
    value :id => 1, :name => 'accept'
    value :id => 2, :name => 'deny'
    value :id => 3, :name => 'pass'
  end
end
</pre>

model:

<code>
class FilterRule < ActiveRecord::Base
  enumerate :policy, :with => ::Policy
...
</code>

**Comment by adzap** [comment]
Not sure if you ever figured this out. I have since dropped formtastic support though. Sorry.
