### ISSUE TITLE
Rails 4 support not available in RubyGems

### ISSUE THREAD

**Issue by dnrce** [adzap/active_enum#35]
The version hasn't been bumped since adding Rails 4 compatibility in 826b9b7f6292b8de4f8643ad3da950f1c092405f, so the update hasn't made it to RubyGems yet. This leaves open issues, e.g. #5.

**Comment by adzap** [comment]
Will release a new gem this week. Sorry this has taken so long.

**Comment by adzap** [comment]
released v1.0.0.pre
