### ISSUE TITLE
Retrieving the key as well as the `id` and `name`

### ISSUE THREAD

**Issue by abepetrillo** [adzap/active_enum#42]
We have the following behaviour:
```ruby
MyApp::Enums::SomeCollection[id] # Translated text representing the key
MyApp::Enums::SomeCollection[key] # The id associated with the key
```

Why is there no easy way of retrieving the `key` which represents the `id`? The closest thing I've found is doing this:

```ruby
arr = MyApp::Enums::SomeCollection.send(:store).send(:_values)
Hash[arr][<id>] # The key I want
```

I would really like to avoid Monkey Patching or calling private methods, and if the maintainers think this is a reasonable requirement I can come up with a pull request.

**Comment by adzap** [comment]
Just was never a need. I wouldn't add a method on the enum classes especially for this given it is specific to i18n. But if you could add one on the store. Happy to look at a pull request.
