### ISSUE TITLE
Formtastic Support

### ISSUE THREAD

**Issue by jcksnparsons** [adzap/active_enum#50]
Hey there!

I'm currently working on upgrading a legacy app that's utilizing Formtastic and have noticed that it looks like the helper for that got removed sometime around 0.9.12. Is there any sort of workaround I can use to reintroduce support for Formtastic? Thanks!

**Comment by adzap** [comment]
I'm not really interested in reintroducing it. Frankly, I should put out the simple form support into own gem, but haven't. 

Just grab the old formtastic extension code and put it in your own local code.

**Comment by jcksnparsons** [comment]
Exactly what I ended up doing, thanks!
