### ISSUE TITLE
String keys in database

### ISSUE THREAD

**Issue by kalsan** [adzap/active_enum#52]
Hi! Your approach looks very promising. There is one feature that might be interesting, but I wasn't able to find it in the README and a glimpse into the code did not reveal it either: does ActiveEnum support String keys (including a String column in the DB)?

Background: https://api.rubyonrails.org/v7.0/classes/ActiveRecord/Enum.html

> Finally it's also possible to use a string column to persist the enumerated value. Note that this will likely lead to slower database queries:

```ruby
class Conversation < ActiveRecord::Base
  enum :status, active: "active", archived: "archived"
end
```

**Comment by adzap** [comment]
No it doesn't and wouldn't easily be able to without significantly breaking the API. I have thought about it and it has been requested.

**Comment by gsmetal** [comment]
@kalsan you could look on my [PR](https://github.com/adzap/active_enum/pull/38) that I used to use many years ago. But it's not updated because I eventually moved to `enumerize`.

**Comment by kalsan** [comment]
@gsmetal thanks for the suggestion! As @adzap pointed out that this will not be implemented, I decided to use this foggy Saturday morning to implement my own, https://github.com/kalsan/anchormodel

It's not quite finished yet, but it appears to work and it's what I'm looking for.

**Comment by kalsan** [comment]
@gsmetal just finished Version 0.0.1, including documentation, fresh out of the press. Feel free to contribute if you are missing features!

**Comment by adzap** [comment]
Nice one. I agree debugging is harder with numeric keys but my use case has required numeric values to be stored.

It’s also case of being backed into a corner by the api. I’ve had string key use cases also but just ended using rails enums for that.
